# Generated by Django 3.2.9 on 2022-02-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FLIGHT',
            fields=[
                ('flight_num', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('dest', models.CharField(max_length=20)),
                ('dist', models.SmallIntegerField()),
                ('quant', models.SmallIntegerField()),
            ],
        ),
    ]
